common:
  debug: false
  gradient_clipping: true
  gradient_clipping_value: 0.1
  log_every: 10
  max_epoch: 100
  num_workers: 10
  save_every: 50
  seed: 42
  test_every: 25
dataset:
  abdominal: 0.5
  bwh: 1
  cfs: 1
  cv: 0
  external: true
  max_length: 144000
  mgh: 0
  mros1: 1
  mros2: 1
  shhs1: 1
  shhs2: 1
  thorax: 0.5
  wsc: 1
discrim:
  disc_hop_lengths:
  - 20
  - 128
  disc_n_ffts:
  - 1024
  - 1024
  disc_win_lengths:
  - 100
  - 512
  filters: 32
  train_discriminator: false
  train_discriminator_prob: 0
  train_discriminator_start_epoch: 0
distributed:
  data_parallel: true
  world_size: 8
exp_details:
  description: 4 hours at 10 hz
  name: no_discrim
loss:
  commit_start_epoch: 30
  weight_commit: 0.25
  weight_feat: 3
  weight_freq: 0.25
  weight_g: 3
  weight_l1: 1
  weight_l2: 0.01
model:
  audio_normalize: false
  bins: 512
  causal: true
  channels: 1
  dimension: 256
  name: my_encodec
  norm: layer_norm
  ratios:
  - 6
  - 5
  - 5
  - 2
  - 1
  sample_rate: 10
  segment: None
  target_bandwidths:
  - 0.32
optimization:
  batch_size: 32
  beta1: 0.8
  beta2: 0.9
  lr: 0.0001
  warmup_epoch: 10
optimizationbatch_size: 16
spectrogram_loss:
  alpha: 0.01
  bandwidth: null
  hop_length: 50
  n_fft: 1024
  win_length: 300
