exp_details:
  name: '091224_l1'
  description: '4 hours at 10 hz'
  date: '2024-12-15'

common:
  save_interval: 2
  test_interval: 5
  log_interval: 1
  max_epoch: 200
  seed: 42
  gradient_clipping: True
  # amp: False

dataset:
  batch_size: 8
  max_length: 144000 # 4 hours at 10 hz
  num_workers: 10
  debug: True

checkpoint:
  save: False
  save_every: 50

optimization:
  lr: 1e-5
  # weight_decay: 1e-6
  disc_lr: 3e-4

loss:
  weight_l1: 1.
  weight_l2: 0.
  weight_commit: 0.
  weight_freq: 0.25
  weight_g: 3.
  weight_feat: 3.
  alpha: 0.01
  bandwidth: None
  n_fft: 1024 # 300 then 512 then 1024

lr_scheduler:
  warmup_epoch: 10

model:
  target_bandwidths: [0.08] #0.1 is 10 codebooks, 0.2 is 20 codebooks
  sample_rate: 10
  channels: 1
  train_discriminator: False # you can set it to 2/3 and other number to train discriminator only
  train_discriminator_prob: 0.5
  audio_normalize: False
  filters: 32
  # ratios: [8, 5, 4, 2] #320 downsampling 
  ratios: [5, 5, 2, 1] # 10 downsampling
  disc_win_lengths: [300]
  disc_hop_lengths: [50]
  disc_n_ffts: [512]
  causal: True
  # norm: 'weight_norm'
  norm: 'layer_norm'
  segment: None
  name: 'my_encodec'
  bins: 256

distributed:
  data_parallel: True
  world_size: 8 

# balancer:
#   weights:
#     l_t: 1
#     l_f: 1
#     # l_g: 3
#     # l_feat: 3